Repository PoCInnovation/EsportOracle, pull requests merged in 2025-06, with the labels that each got.

#30 feat: add EsportOracleRequester contract for match request handling
  esportOracle.sol
  oracle/src/esportOracleRequester.sol
Labels: enhancement

#28 🔨 Script: add script docker contract deployement
  oracle/Dockerfile
  oracle/Dockerfile.anvil
  oracle/deploy_oracle.sh
  oracle/docker-compose.yml
  oracle/script.sh
Labels: enhancement

#31 enhance README
  README.md
Labels: documentation

#35 Fix ban condition
  oracle/src/esportOracle.sol
Labels: bug
